add editmode response on language = empty-string
dachcom-digital/pimcore-i18n pull request #103
Opened 2022-10-06 07:36 UTC by GALCF

If the document was already saved with a language property and you remove the language later, it will not be null but an empty string

2022-11-15 07:35 UTC, solverat requested changes

2022-11-15 07:35 UTC, solverat commented on src/I18nBundle/EventListener/I18nStartupListener.php
> +        if (!$document->getProperty('language')) {
please use `!empty()`.

2022-11-15 07:35 UTC, solverat commented
@GALCF True, thank you! I added my review and rebased your branch.

2022-11-15 10:38 UTC, ChristianFlack commented on src/I18nBundle/EventListener/I18nStartupListener.php
> +        if (!$document->getProperty('language')) {
done :)

2022-11-16 11:57 UTC, solverat approved these changes

2022-11-16 11:57 UTC, solverat commented on src/I18nBundle/EventListener/I18nStartupListener.php
> +        if (!$document->getProperty('language')) {
@ChristianFlack awesome! Thanks!

2022-11-16 12:04 UTC, merged